name: core_cai_v3
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  easy_rich_text: ^1.0.3
  url_launcher: ^6.0.20
  extended_image: ^6.0.1
  transparent_image: ^2.0.0
  file_picker: ^4.5.1
  flutter_svg: ^1.0.3
  image_picker: ^0.8.4+10
  intl: ^0.17.0
  drop_zone: ^1.0.2
  flutter_overlay_loader: ^1.0.3
  easy_dynamic_theme: ^2.2.0
  flutter_bloc: ^8.1.1
  progress_indicators: ^1.0.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
